---

- name: say 'install openssl'
  hosts: k8s
  become: false
  tasks:
    - name: install apt packages
      apt: name=openssl state=present
      when: ansible_pkg_mgr == "apt"
    
    - name: install yum packages
      yum: name=openssl state=present
      when: ansible_pkg_mgr == "yum"
